### ISSUE TITLE
Define the meaing of the "pay-as-you-go" aproach

### ISSUE THREAD

**Issue by PiotrekDlang** [JinShil/utiliD#10]
Hello

I think it would be nice to have some kind of idea what "pay-as-you-go" means in practice for D.

I read some related discussions on GitHub and on the D forums. But the current picture is too vague for me.

How in practice user will control the usage of "computer resource" while using D features?

**Comment by JinShil** [comment]
It's probably easier to understand by examining some cases that aren't pay as you go.

When I first started using D, I was try to write microcontroller firmware for the ARM Cortex-M.  All I needed to do what read and write to memory-mapped IO, so I didn't need all of the runtime features of D.  However, I wanted to use structs to model a register.  I added `struct MyRegister { }` and then the compiler emitted an error saying something to the effect of "cannot find `TypeInfo_Struct`".  It turns out I had to add `class TypeInfo_Struct {}` to my object.d file to get past the error, but `TypeInfo_Struct` also inherits from `class TypeInfo`, so I had to add `class TypeInfo { }` and `class TypeInfo_Struct : TypeInfo {}` to my object.d file.  Then the compiler generated another error saying the size of `TypeInfo_Struct` did not match the size the runtime expected, so I had to add something like `class TypeInfo_Struct : TypeInfo { ubyte[22] nonsense; }` to my object.d file, and I was finally able to get a build.

What's sad in all of that is that I'm my code wasn't even utilizing runtime type information (i.e. `TypeInfo`), so none of that code that I had to write ever even ended up in the resulting binary.  That experience was NOT a pay-as-you-go experience. That problem has since been resoved with a few PRs I submitted and were released with 2.079.  

 * #7395 and #7768 for opt-in `ModuleInfo`
 * #7786 for opt-in `Throwable`
 * #7799 for opt-in `TypeInfo`

But there's more.

Currently, if you use certain features of D, like arrays, the compiler lowers expressions to [runtime hooks](https://wiki.dlang.org/Runtime_Hooks) like [`_d_arraysetlengthT`](https://github.com/dlang/druntime/blob/e47a00bff935c3f079bb567a6ec97663ba384487/src/rt/lifetime.d#L1265).  That runtime hook depends on `TypeInfo`.  `TypeInfo` is a class, so depends on the runtime's class support, and classes, in general, have a dependency on the garbage collector.  However, everything `_d_arraysetlengthT` needs from `TypeInfo` it knows at compile time.  So, if we could simply replace that runtime hook with a template that accepts a compile-time type parameter, then we reduce the dependency on `TypeInfo` which reduces the dependency on classes, which reduces the dependency on the garbage collector (Actually, that's not entirely true because setting the length of an array could result in an allocation, but the principle still holds true).  So, that is also NOT a pay-as-you-go experience.

Finally, let's take a look at a minimal hello world program:

```D
module object;
```

```D
module main;

void main() { }
```
```
dmd main.d
size main
   text    data     bss     dec     hex filename
 503230   51544    2544  557318   88106 main
ldd main
	linux-vdso.so.1 (0x00007ffe9f126000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fe0d233c000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fe0d21f6000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007fe0d21ec000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fe0d21e7000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fe0d21cd000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fe0d2008000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe0d2439000)
```

Look at how big that binary is and how many library dependencies there are.  That is NOT pay-as-you-go.  Contrast that with this:

```D
module main;

alias immutable(char)[] string;

private long __d_sys_write(long arg1, in void* arg2, long arg3)
{
    long result;

    asm
    {
        mov RAX, 1;
        mov RDI, arg1;
        mov RSI, arg2;
        mov RDX, arg3;
        syscall;
    }

    return result;
}

void write(string text)
{
    __d_sys_write(2, text.ptr, text.length);
}

private void __d_sys_exit(long arg1)
{
    asm
    {
        mov RAX, 60;
        mov RDI, arg1;
        syscall;
    }
}

void main();
extern(C) void _start()
{
    main();
    __d_sys_exit(0);
}

void main()
{
    write("Hello, World!\n");
}
```

```
dmd -lib -c main.d -of=main.o
ld main.o -o main
size main
   text	   data	    bss	    dec	    hex	filename
    176	      0	      0	    176	     b0	main
ldd main
	not a dynamic executable
```

The first program should have produced a small executable, much like the second.  But, the language/compiler is not able to do that at this time.  That is what I'm currently trying to fix with the language/compiler.  A simple Hello World program like the second illustrated above, should be a very small executable, and that starts the opt-in continuum.  From there you the only things that ends up in your binary, and the only things that the binary links to, are the bare minimum for what the program requires to run.  The compiler should also not require any symbols to get a build, except for what is required by the program being compiled.

I don't know if gave you what you were looking for.  If it didn't, please keep the discussion going.

**Comment by PiotrekDlang** [comment]
OK. So one thing is to remove unneeded code. I think it's clear. The other is how to tell the compiler how much you are able to pay for the certain language contracts. Do you want to achieve that with import mechanics, or command line switches or attributes, etc? Like, let say I don't want to use a certain compiler generated code. 

Should we provide that kind of mechanism or it is useless in your opinion?

**Comment by JinShil** [comment]
> Do you want to achieve that with import mechanics, or command line switches or attributes, etc?

I definitely don't want command-line switches.  The way to not pay for something you don't want is to simply not use it.  There are two ways to do that that I've discovered so far:
1. Break the features up into logic pay-as-you-go modules and import only what you need.  I'm calling this "Language as a library" for lack of a better term.
2. Implicitly import everything, but everything must be a template.  Since templates are only used when they're instantiated, the user opts into a feature by using it and the compiler instantiates the template that was implicitly imported.

I generally prefer (1), but @andrei and I think @atilaneves appear to support (2).  I haven't decided yet what's best, but if I had to choose today I'd take (1).  I'm also open to other ideas, perhaps there's something I haven't thought of yet.

**Comment by JinShil** [comment]
> Like, let say I don't want to use a certain compiler generated code.

I don't think D does much "code generation" in the context you're referring to.  Instead, with D, the compiler lowers expressions to function calls.  So, for example, if you were to compare two objects (e.g. ` if (obj1 < obj2) { }` the compiler lowers that expression to [`object.__cmp`](https://github.com/dlang/druntime/blob/b5a95a2a85d8da441e1f2a9633c0bd0174451cb6/src/object.d#L115-L126).  The only code the compiler "generates" is the *call* to `object.__cmp`.  So, for D, the "generated code" is already in the library (a.ka. druntime).

**Comment by lesderid** [comment]
> 1. Break the features up into logical pay-as-you-go modules and import only what you need.  I'm calling this "Language as a library" for lack of a better term.

How would this work without breaking existing code? Do correct me if I'm misunderstanding what you're saying, but aren't we also further conflating language features with (d)runtime responsibilities if we go with this route? How would something like `import feature.classes` be implemented without increasing the coupling between the compiler and the runtime library (or without giving certain module names a special meaning in the compiler)?

**Comment by JinShil** [comment]
> How would this work without breaking existing code?

**Comment by lesderid** [comment]
Ah, that clears things up. I wrongly assumed you were proposing to somehow be able to toggle the actual lowerings by the compiler with imports. If I understand correctly, essentially what you're proposing is just to properly modularise/packagise the functions the language features lower to? Publicly importing them in the `object.d` should indeed work then.

**Comment by PiotrekDlang** [comment]
> I haven't thought it all the way through, but if the existing druntime were to just publicly import all of the language feature modules into object.d, it should work.

@JinShil This sounds interesting. This looks like someone can use a file to define a subset of the language features for a particular application submodule.

**Comment by PiotrekDlang** [comment]
OK. I think this can be closed as the initial picture is clear. I'm slowly going back to work on new test cases and documentation. I successfully ran the "HelloWorld" code on a bare linux container (LXC). Using LXC solution for verifying this code is fun and keeps me motivated so I plan to open a PR after I finish my experiments.
